<div class="row">
    <div class="col-md-12">
        <strong>
            Integração com Web Service do Correios. Veja o demo online. Consulta preços e prazos, imprime etiquetas e PLP, etc.
        </strong>
        
        <div class="alert-message alert-message-info">
            <p>
                <small>Esta documentação está em construção</small>.
            </p>
            <p>
                <small>
                    Em breve teremos mais explicações sobre cada demonstração exposta abaixo.
                </small>
            </p>
        </div>
    </div>
</div>

